# NumPy Practice Notebook

## 1. Introduction to NumPy

In [1]:
import numpy as np

## 2. Creating Arrays

In [2]:
array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(array_1d)

1D Array:
[10 20 30 40 50]


In [3]:
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(array_2d)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 3. Array Properties

In [5]:
print("1D Array Dimensions:", array_1d.ndim)
print("2D Array Dimensions:", array_2d.ndim)
print("3D Array Dimensions:", array_3d.ndim)

1D Array Dimensions: 1
2D Array Dimensions: 2
3D Array Dimensions: 3


In [6]:
print("1D Shape:", array_1d.shape)
print("2D Shape:", array_2d.shape)
print("3D Shape:", array_3d.shape)

1D Shape: (5,)
2D Shape: (3, 3)
3D Shape: (2, 2, 3)


In [7]:
print("Data Type of 1D Array:", array_1d.dtype)
print("Data Type of 2D Array:", array_2d.dtype)
print("Data Type of 3D Array:", array_3d.dtype)

Data Type of 1D Array: int64
Data Type of 2D Array: int64
Data Type of 3D Array: int64


# Check Number of Elements

In [8]:
print("Elements in 1D:", array_1d.size)
print("Elements in 2D:", array_2d.size)
print("Elements in 3D:", array_3d.size)

Elements in 1D: 5
Elements in 2D: 9
Elements in 3D: 12


## 4. Indexing and Slicing

In [9]:
print("First element:", array_1d[0])
print("Third element:", array_1d[2])
print("Last element:", array_1d[-1])

First element: 10
Third element: 30
Last element: 50


In [10]:
print("First row, first column:", array_2d[0, 0])
print("Second row, third column:", array_2d[1, 2])
print("Third row, second column:", array_2d[2, 1])

First row, first column: 10
Second row, third column: 60
Third row, second column: 80


# Indexing in 3D Array

In [11]:
print("Element:", array_3d[0, 1, 2])

Element: 6


# Slicing 1D Array

In [12]:
print("First three elements:", array_1d[:3])
print("Elements from index 2:", array_1d[2:])
print("Every second element:", array_1d[::2])

First three elements: [10 20 30]
Elements from index 2: [30 40 50]
Every second element: [10 30 50]


### Slicing 2D Array

In [13]:
data_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("First two rows:")
print(data_2d[:2])

print("\nFirst two columns:")
print(data_2d[:, :2])

First two rows:
[[1 2 3]
 [4 5 6]]

First two columns:
[[1 2]
 [4 5]
 [7 8]]


## 5. Reshaping Arrays

In [14]:
numbers = np.arange(1, 13)

reshaped_array = numbers.reshape(3, 4)

print("Original Array:")
print(numbers)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 6. Array Generation Functions

In [15]:
zero_array = np.zeros((3, 4))

print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
one_array = np.ones((3, 4))

print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
range_array = np.arange(1, 21, 2)

print(range_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
linear_array = np.linspace(0, 10, 6)

print(linear_array)

[ 0.  2.  4.  6.  8. 10.]


## 7. Mathematical Operations

In [19]:
array_a = np.array([10, 20, 30, 40])
array_b = np.array([1, 2, 3, 4])

result = array_a + array_b

print("Addition:", result)

Addition: [11 22 33 44]


In [20]:
array_a = np.array([10, 20, 30, 40])
array_b = np.array([1, 2, 3, 4])

result = array_a - array_b

print("Subtraction:", result)

Subtraction: [ 9 18 27 36]


In [21]:
array_a = np.array([10, 20, 30, 40])
array_b = np.array([1, 2, 3, 4])

result = array_a * array_b

print("Multiplication:", result)

Multiplication: [ 10  40  90 160]


In [22]:
array_a = np.array([10, 20, 30, 40])
array_b = np.array([1, 2, 3, 4])

result = array_a / array_b

print("Division:", result)

Division: [10. 10. 10. 10.]


In [23]:
numbers = np.array([2, 4, 6, 8])

print("Square:", numbers ** 2)
print("Square Root:", np.sqrt(numbers))

Square: [ 4 16 36 64]
Square Root: [1.41421356 2.         2.44948974 2.82842712]


## 8. Vectorized Operations

In [24]:
marks = np.array([50, 60, 70, 80, 90])

updated_marks = marks + 5

print("Original Marks:", marks)
print("Updated Marks:", updated_marks)

Original Marks: [50 60 70 80 90]
Updated Marks: [55 65 75 85 95]


## 9. Boolean Masking

In [25]:
marks = np.array([35, 45, 55, 65, 75, 85, 95])

passed_students = marks >= 50

print("Boolean Mask:")
print(passed_students)

print("\nMarks >= 50:")
print(marks[passed_students])

Boolean Mask:
[False False  True  True  True  True  True]

Marks >= 50:
[55 65 75 85 95]


In [26]:
numbers = np.array([10, 25, 40, 55, 70, 85, 100])

filtered_values = numbers[numbers > 50]

print("Values greater than 50:")
print(filtered_values)

Values greater than 50:
[ 55  70  85 100]


## 10. Broadcasting

In [27]:
prices = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

discount = 50

final_prices = prices - discount

print("Original Prices:")
print(prices)

print("\nAfter Discount:")
print(final_prices)

Original Prices:
[[100 200 300]
 [400 500 600]]

After Discount:
[[ 50 150 250]
 [350 450 550]]


In [28]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

addition = np.array([1, 2, 3])

result = data + addition

print(result)

[[11 22 33]
 [41 52 63]]


## 11. Aggregate Functions

In [29]:
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))

Sum: 150


In [30]:
numbers = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(numbers))

Mean: 30.0


In [31]:
numbers = np.array([10, 20, 30, 40, 50])

print("Minimum:", np.min(numbers))

Minimum: 10


In [32]:
numbers = np.array([10, 20, 30, 40, 50])

print("Maximum:", np.max(numbers))

Maximum: 50


In [33]:
numbers = np.array([10, 20, 30, 40, 50])

print("Median:", np.median(numbers))

Median: 30.0


In [34]:
numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)
print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


In [35]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Total:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Total: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Median: 50.0


In [36]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Row-wise Sum:", np.sum(data, axis=1))
print("Column-wise Sum:", np.sum(data, axis=0))

Row-wise Sum: [ 60 150 240]
Column-wise Sum: [120 150 180]


## 12. Practical Example: Student Marks Analysis

In [37]:
marks = np.array([78, 85, 92, 67, 88, 95, 73, 81])

print("Student Marks:", marks)
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Median Marks:", np.median(marks))

print("\nStudents scoring above 80:")
print(marks[marks > 80])

Student Marks: [78 85 92 67 88 95 73 81]
Average Marks: 82.375
Highest Marks: 95
Lowest Marks: 67
Median Marks: 83.0

Students scoring above 80:
[85 92 88 95 81]
